FROM node:22-alpine AS build
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build

FROM php:8.3-cli
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      libpq-dev curl unzip git && \
    rm -rf /var/lib/apt/lists/*
RUN docker-php-ext-install pdo_pgsql
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
WORKDIR /app
COPY composer.json composer.lock ./
RUN COMPOSER_POLICY_ADVISORIES_BLOCK=false composer install --no-interaction --no-progress --no-scripts
COPY . .
COPY --from=build /app/public/build ./public/build
RUN cp .env.example .env && \
    composer dump-autoload && \
    php artisan package:discover --ansi && \
    php artisan key:generate --ansi && \
    chmod -R 777 storage bootstrap/cache
