source "https://rubygems.org"

gem "rails", "~> 8.1.3"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "bootsnap", require: false

gem "sidekiq", "~> 7.0"
gem "redis", "~> 5.0"
gem "rack-cors"
gem "kaminari"
gem "rack-attack"
gem "aws-sdk-secretsmanager"
gem "aws-sdk-s3"

gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "rspec-rails", "~> 7.0"
  gem "factory_bot_rails"
  gem "webmock"
end

group :development do
  gem "rubocop-rails", require: false
end
