"""
Mapeamento de tags do Stack Overflow para as categorias do TechMind.

Cada tag do SO é mapeada para uma das 8 categorias do sistema.
Usado pelo script prepare_dataset.py para transformar dados brutos
do Stack Overflow em dados de treino rotulados.
"""

TAG_TO_CATEGORY = {
    # === Backend ===
    "ruby-on-rails": "Backend",
    "ruby": "Backend",
    "python": "Backend",
    "java": "Backend",
    "node.js": "Backend",
    "express": "Backend",
    "django": "Backend",
    "flask": "Backend",
    "spring": "Backend",
    "spring-boot": "Backend",
    "php": "Backend",
    "laravel": "Backend",
    "c#": "Backend",
    "asp.net": "Backend",
    "asp.net-core": "Backend",
    "go": "Backend",
    "rust": "Backend",
    "scala": "Backend",
    "postgresql": "Backend",
    "mysql": "Backend",
    "mongodb": "Backend",
    "sqlite": "Backend",
    "redis": "Backend",
    "sql": "Backend",
    "database": "Backend",
    "api": "Backend",
    "rest": "Backend",
    "graphql": "Backend",
    "websocket": "Backend",
    "rabbitmq": "Backend",
    "kafka": "Backend",
    "grpc": "Backend",
    "activerecord": "Backend",
    "sequelize": "Backend",
    "prisma": "Backend",
    "typeorm": "Backend",
    "entity-framework": "Backend",
    "hibernate": "Backend",
    "jpa": "Backend",
    "sqlalchemy": "Backend",
    "celery": "Backend",
    "sidekiq": "Backend",

    # === Frontend ===
    "javascript": "Frontend",
    "typescript": "Frontend",
    "reactjs": "Frontend",
    "angular": "Frontend",
    "vue.js": "Frontend",
    "vuejs": "Frontend",
    "svelte": "Frontend",
    "next.js": "Frontend",
    "nuxt.js": "Frontend",
    "gatsby": "Frontend",
    "html": "Frontend",
    "css": "Frontend",
    "sass": "Frontend",
    "less": "Frontend",
    "tailwind-css": "Frontend",
    "bootstrap": "Frontend",
    "material-ui": "Frontend",
    "chakra-ui": "Frontend",
    "jquery": "Frontend",
    "webpack": "Frontend",
    "vite": "Frontend",
    "redux": "Frontend",
    "mobx": "Frontend",
    "rxjs": "Frontend",
    "cypress": "Frontend",
    "jest": "Frontend",
    "storybook": "Frontend",
    "three.js": "Frontend",
    "d3.js": "Frontend",
    "chart.js": "Frontend",
    "ajax": "Frontend",
    "webgl": "Frontend",
    "progressive-web-apps": "Frontend",
    "responsive-design": "Frontend",
    "frontend": "Frontend",
    "ecmascript-6": "Frontend",
    "dom": "Frontend",

    # === DevOps & Infraestrutura ===
    "docker": "DevOps & Infraestrutura",
    "kubernetes": "DevOps & Infraestrutura",
    "terraform": "DevOps & Infraestrutura",
    "ansible": "DevOps & Infraestrutura",
    "puppet": "DevOps & Infraestrutura",
    "chef": "DevOps & Infraestrutura",
    "jenkins": "DevOps & Infraestrutura",
    "gitlab-ci": "DevOps & Infraestrutura",
    "github-actions": "DevOps & Infraestrutura",
    "circleci": "DevOps & Infraestrutura",
    "aws": "DevOps & Infraestrutura",
    "amazon-web-services": "DevOps & Infraestrutura",
    "azure": "DevOps & Infraestrutura",
    "google-cloud-platform": "DevOps & Infraestrutura",
    "gcp": "DevOps & Infraestrutura",
    "nginx": "DevOps & Infraestrutura",
    "apache": "DevOps & Infraestrutura",
    "linux": "DevOps & Infraestrutura",
    "bash": "DevOps & Infraestrutura",
    "shell": "DevOps & Infraestrutura",
    "prometheus": "DevOps & Infraestrutura",
    "grafana": "DevOps & Infraestrutura",
    "vagrant": "DevOps & Infraestrutura",
    "elasticsearch": "DevOps & Infraestrutura",
    "logstash": "DevOps & Infraestrutura",
    "kibana": "DevOps & Infraestrutura",
    "helm": "DevOps & Infraestrutura",
    "istio": "DevOps & Infraestrutura",
    "devops": "DevOps & Infraestrutura",
    "ci-cd": "DevOps & Infraestrutura",
    "continuous-integration": "DevOps & Infraestrutura",
    "continuous-deployment": "DevOps & Infraestrutura",
    "monitoring": "DevOps & Infraestrutura",
    "infrastructure-as-code": "DevOps & Infraestrutura",
    "load-balancing": "DevOps & Infraestrutura",
    "reverse-proxy": "DevOps & Infraestrutura",
    "ssl-certificate": "DevOps & Infraestrutura",
    "lets-encrypt": "DevOps & Infraestrutura",

    # === Dados & ML ===
    "machine-learning": "Dados & ML",
    "deep-learning": "Dados & ML",
    "tensorflow": "Dados & ML",
    "pytorch": "Dados & ML",
    "scikit-learn": "Dados & ML",
    "pandas": "Dados & ML",
    "numpy": "Dados & ML",
    "nlp": "Dados & ML",
    "natural-language-processing": "Dados & ML",
    "data-science": "Dados & ML",
    "computer-vision": "Dados & ML",
    "statistics": "Dados & ML",
    "r": "Dados & ML",
    "jupyter-notebook": "Dados & ML",
    "matplotlib": "Dados & ML",
    "seaborn": "Dados & ML",
    "plotly": "Dados & ML",
    "dataframe": "Dados & ML",
    "etl": "Dados & ML",
    "data-warehouse": "Dados & ML",
    "data-pipeline": "Dados & ML",
    "apache-spark": "Dados & ML",
    "pyspark": "Dados & ML",
    "dask": "Dados & ML",
    "xgboost": "Dados & ML",
    "neural-network": "Dados & ML",
    "regression": "Dados & ML",
    "classification": "Dados & ML",
    "clustering": "Dados & ML",
    "time-series": "Dados & ML",
    "recommender-system": "Dados & ML",
    "llm": "Dados & ML",
    "large-language-model": "Dados & ML",
    "langchain": "Dados & ML",
    "ai": "Dados & ML",
    "artificial-intelligence": "Dados & ML",
    "genai": "Dados & ML",

    # === Mobile ===
    "android": "Mobile",
    "ios": "Mobile",
    "swift": "Mobile",
    "swiftui": "Mobile",
    "kotlin": "Mobile",
    "react-native": "Mobile",
    "flutter": "Mobile",
    "dart": "Mobile",
    "xamarin": "Mobile",
    "ionic-framework": "Mobile",
    "cordova": "Mobile",
    "jetpack-compose": "Mobile",
    "uikit": "Mobile",
    "firebase": "Mobile",
    "push-notification": "Mobile",
    "google-play": "Mobile",
    "app-store": "Mobile",
    "mobile-development": "Mobile",
    "cross-platform": "Mobile",
    "expo": "Mobile",
    "android-studio": "Mobile",
    "xcode": "Mobile",
    "mobile": "Mobile",

    # === Segurança ===
    "security": "Segurança",
    "cybersecurity": "Segurança",
    "authentication": "Segurança",
    "authorization": "Segurança",
    "oauth": "Segurança",
    "oauth-2.0": "Segurança",
    "jwt": "Segurança",
    "json-web-token": "Segurança",
    "encryption": "Segurança",
    "cryptography": "Segurança",
    "https": "Segurança",
    "ssl": "Segurança",
    "tls": "Segurança",
    "csrf": "Segurança",
    "xss": "Segurança",
    "sql-injection": "Segurança",
    "owasp": "Segurança",
    "penetration-testing": "Segurança",
    "penetration-test": "Segurança",
    "vulnerability": "Segurança",
    "cors": "Segurança",
    "rbac": "Segurança",
    "access-control": "Segurança",
    "hash": "Segurança",
    "bcrypt": "Segurança",
    "password": "Segurança",
    "secret-management": "Segurança",
    "security-headers": "Segurança",
    "zero-trust": "Segurança",

    # === Arquitetura & Design ===
    "design-patterns": "Arquitetura & Design",
    "microservices": "Arquitetura & Design",
    "microservice-architecture": "Arquitetura & Design",
    "software-architecture": "Arquitetura & Design",
    "architecture": "Arquitetura & Design",
    "domain-driven-design": "Arquitetura & Design",
    "ddd": "Arquitetura & Design",
    "clean-architecture": "Arquitetura & Design",
    "solid": "Arquitetura & Design",
    "solid-principles": "Arquitetura & Design",
    "cqrs": "Arquitetura & Design",
    "event-sourcing": "Arquitetura & Design",
    "hexagonal-architecture": "Arquitetura & Design",
    "onion-architecture": "Arquitetura & Design",
    "clean-code": "Arquitetura & Design",
    "refactoring": "Arquitetura & Design",
    "uml": "Arquitetura & Design",
    "object-oriented": "Arquitetura & Design",
    "functional-programming": "Arquitetura & Design",
    "event-driven-architecture": "Arquitetura & Design",
    "serverless": "Arquitetura & Design",
    "soa": "Arquitetura & Design",
    "mvc": "Arquitetura & Design",
    "mvvm": "Arquitetura & Design",
    "system-design": "Arquitetura & Design",
    "scalability": "Arquitetura & Design",
    "distributed-system": "Arquitetura & Design",
    "software-design": "Arquitetura & Design",

    # === Carreira & Soft Skills ===
    "career-development": "Carreira & Soft Skills",
    "career": "Carreira & Soft Skills",
    "code-review": "Carreira & Soft Skills",
    "agile": "Carreira & Soft Skills",
    "scrum": "Carreira & Soft Skills",
    "kanban": "Carreira & Soft Skills",
    "team-management": "Carreira & Soft Skills",
    "management": "Carreira & Soft Skills",
    "productivity": "Carreira & Soft Skills",
    "time-management": "Carreira & Soft Skills",
    "technical-debt": "Carreira & Soft Skills",
    "mentoring": "Carreira & Soft Skills",
    "leadership": "Carreira & Soft Skills",
    "communication": "Carreira & Soft Skills",
    "interview": "Carreira & Soft Skills",
    "resume": "Carreira & Soft Skills",
    "freelance": "Carreira & Soft Skills",
    "remote-work": "Carreira & Soft Skills",
    "work-life-balance": "Carreira & Soft Skills",
    "open-source": "Carreira & Soft Skills",
    "documentation": "Carreira & Soft Skills",
    "pair-programming": "Carreira & Soft Skills",
    "code-quality": "Carreira & Soft Skills",
    "estimation": "Carreira & Soft Skills",
}

# Categorias válidas do TechMind
VALID_CATEGORIES = set(TAG_TO_CATEGORY.values())

def map_tags_to_category(tags: list[str]) -> str | None:
    """Mapeia uma lista de tags do SO para a categoria TechMind mais provável.

    Retorna a categoria com mais tags correspondentes, ou None se nenhuma
    tag for reconhecida.
    """
    matches: dict[str, int] = {}
    for tag in tags:
        tag_lower = tag.strip().lower()
        if tag_lower in TAG_TO_CATEGORY:
            cat = TAG_TO_CATEGORY[tag_lower]
            matches[cat] = matches.get(cat, 0) + 1

    if not matches:
        return None

    # Retorna a categoria com mais correspondências
    return max(matches, key=matches.get)
